### ISSUE TITLE
注意等比缩放

### ISSUE THREAD

**Issue by YuStephen** [yuxunhuang/HYClipIconViewController#1]
你在正方形裁剪完之后，应该做一个尺寸判断，比如if (clipImage.size.width > 480 || clipImage.size.height > 480) ，然后大于之后等比例缩放，保证尺寸在480以下。你可以在源代码基础上使用高清图片尝试下，如果不做这一步，你的rationScale会把原图的尺寸变的特别大，这样的话，如果想保存裁剪完的图片是特别大的

**Comment by yuxunhuang** [comment]
您好，感谢您提的问题，我也使用1900*1200的高清图片试了下，裁剪之后的图片并不会超过裁剪宽的尺寸。我在HYClipIconViewController中（- (UIImage *)scaleImageSizeWith:(UIImage *)image）在图片进行裁剪之前就已经做了缩放的操作。所以并不会出现尺寸过大的情况。
